apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: redisclusters.operator.java.developer.alan.com
spec:
  group: operator.java.developer.alan.com
  versions:
    - name: v1beta
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 3
                  default: 3
            status:
              type: object
              properties:
                creationDate:
                  type: number
                availableReplicas:
                  type: integer

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: redisclusters
    # singular name to be used as an alias on the CLI and for display
    singular: rediscluster
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: RedisCluster
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - rc